[package]
name = "bpspice-py"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "bpspice"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.4", features = ["extension-module"] }
bpspice = { workspace = true }