[package]
name = "gspice-py"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "gspice"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
gspice.workspace = true