[package]
name = "gspice-py"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "gspice"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.4", features = ["extension-module"] }
gspice = { workspace = true }